"""Source registry.

Sources live in plain-text files under ``sources/`` so they are easy to review
and extend (one source per line, ``#`` starts a comment):

``sources/github.txt``      curated, hand-picked proxy lists hosted on GitHub
``sources/websites.txt``    curated websites / APIs / pages (many languages)
``sources/discovered.txt``  generated by ``src/discover.py`` (GitHub search),
                            capped at 50,000 sources

Line formats::

    <hint> <owner>/<repo>/<branch>/<path>                       # github.txt, discovered.txt
    <hint> <url> [pages=1..10] [step=64]                         # websites.txt

``hint`` is the protocol the source claims for entries that carry no protocol
of their own: ``http``, ``socks4``, ``socks5``, ``socks`` (4+5) or ``mixed``.
A paged line has ``{page}`` (1, 2, 3 ...) and/or ``{offset}`` (``(page-1)*step``)
in its URL; pages are fetched in order until one returns nothing new.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

VALID_HINTS = frozenset({"http", "https", "socks", "socks4", "socks5", "mixed"})
MAX_DISCOVERED = 50_000


@dataclass(frozen=True, slots=True)
class Source:
    hint: str
    urls: tuple[str, ...]            # primary first, then fallback mirrors
    kind: str = "web"                # github | discovered | web
    pages: tuple[int, int] | None = None
    step: int = 1

    @property
    def key(self) -> str:
        """Stable identity used by the health tracker."""
        return self.urls[0]

    @property
    def paged(self) -> bool:
        return self.pages is not None


def github_urls(path: str) -> tuple[str, ...]:
    """Raw URL followed by CDN mirrors for ``owner/repo/branch/file``."""
    owner, repo, branch, *rest = path.split("/")
    rel = "/".join(rest)
    return (
        f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{rel}",
        f"https://cdn.jsdelivr.net/gh/{owner}/{repo}@{branch}/{rel}",
        f"https://cdn.statically.io/gh/{owner}/{repo}/{branch}/{rel}",
    )


def parse_github_line(line: str, kind: str = "github") -> Source | None:
    parts = line.split("#", 1)[0].split()
    if len(parts) != 2:
        return None
    hint, path = parts[0].lower(), parts[1].strip("/")
    if hint not in VALID_HINTS or len(path.split("/")) < 4:
        return None
    return Source(hint, github_urls(path), kind)


_RANGE_RE = re.compile(r"^(\d+)\.\.(\d+)$")


def parse_web_line(line: str) -> Source | None:
    parts = line.split("#", 1)[0].split()
    if len(parts) < 2:
        return None
    hint, url = parts[0].lower(), parts[1]
    if hint not in VALID_HINTS or not url.startswith(("http://", "https://")):
        return None
    pages = None
    step = 1
    for option in parts[2:]:
        name, _, value = option.partition("=")
        if name == "pages":
            match = _RANGE_RE.match(value)
            if not match or int(match.group(1)) > int(match.group(2)):
                return None
            pages = (int(match.group(1)), int(match.group(2)))
        elif name == "step" and value.isdigit():
            step = max(1, int(value))
    if pages is None and ("{page}" in url or "{offset}" in url):
        return None  # template without a page range
    return Source(hint, (url,), "web", pages, step)


def _read(path: Path) -> list[str]:
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return []


def load_sources(root: str | Path = "sources", *, include_discovered: bool = True,
                 limit_discovered: int = MAX_DISCOVERED) -> tuple[list[Source], dict[str, int]]:
    """Load every registered source. Curated entries win over discovered ones."""
    root = Path(root)
    sources: list[Source] = []
    seen: set[str] = set()
    counts = {"github": 0, "websites": 0, "discovered": 0}

    def add(source: Source | None, bucket: str) -> None:
        if source is None or source.key in seen:
            return
        seen.add(source.key)
        sources.append(source)
        counts[bucket] += 1

    for line in _read(root / "github.txt"):
        add(parse_github_line(line, "github"), "github")
    for line in _read(root / "websites.txt"):
        add(parse_web_line(line), "websites")
    if include_discovered:
        for line in _read(root / "discovered.txt"):
            if counts["discovered"] >= limit_discovered:
                break
            add(parse_github_line(line, "discovered"), "discovered")
    return sources, counts
